# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # services:
    #   mariadb:
    #     image: mariadb:latest
    #     ports:
    #       - 3306
    #     env:
    #       MYSQL_USER: root
    #       MYSQL_PASSWORD: 12345
    #       MYSQL_DATABASE: course_work
    #       MYSQL_ROOT_PASSWORD: 12345
    #     options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
    
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        javafx: true
        cache: maven

    - uses: actions/checkout@v1

    # - name: Verify MariaDB connection
    #   env:
    #       PORT: ${{ job.services.mariadb.ports[3306] }}
    #   run: |
    #       while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
    #         sleep 1
    #       done     
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        # host port: 3800 # Optional, default value is 3306. The port of host
        # container port: 3307 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0.33' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'course_work'
        mysql root password: '12345'
        mysql user: 'root'
        mysql password: '12345'

    - name: Build with Maven
      run: mvn -B package --file Program/tradeCompany/pom.xml
    - run: mkdir staging && cp Program/tradeCompany/target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
  
    # - name: Test
    #   run: |
    #         your tests
